plugins { id 'com.android.application' }

android {
    namespace 'app.saleh.telpotest'
    compileSdk 34

    defaultConfig {
        applicationId 'app.saleh.telpotest'
        minSdk 23
        targetSdk 34
        versionCode 5
        versionName '1.4-m1-official-aar'
    }
}

dependencies {
    implementation files('libs/demoSDK_v2.28.20241212.aar')
}
