plugins { id 'com.android.application' }

android {
    namespace 'app.saleh.telpotest'
    compileSdk 34

    defaultConfig {
        applicationId 'app.saleh.telpotest'
        minSdk 23
        targetSdk 34
        versionCode 3
        versionName '1.2-m1-native-print'
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }
}

dependencies {
    implementation files('libs/telpo_api.jar')
}
