'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type Tab='dashboard'|'orders'|'products'|'categories'|'modifiers'|'branches'|'availability'|'promotions'|'customers'|'reports'|'settings';
type Category={id:string;nameAr:string;nameEn?:string|null;sortOrder:number;isActive:boolean;_count?:{products:number}};
type BranchProduct={branchId:string;productId:string;isAvailable:boolean;priceOverride?:string|null};
type BranchModifier={branchId:string;modifierId:string;isAvailable:boolean};
type Modifier={id:string;modifierGroupId:string;nameAr:string;nameEn?:string|null;priceDelta:string;isActive:boolean;branchModifiers:BranchModifier[]};
type ModifierGroup={id:string;productId:string;nameAr:string;nameEn?:string|null;selectionType:string;isRequired:boolean;isActive:boolean;product:{id:string;nameAr:string;nameEn?:string|null};modifiers:Modifier[]};
type Product={id:string;sku:string;nameAr:string;nameEn?:string|null;descriptionAr?:string|null;imageUrl?:string|null;basePrice:string;isActive:boolean;sortOrder:number;categoryId?:string|null;category?:Category|null;branchProducts:BranchProduct[];modifierGroups?:ModifierGroup[]};
type Branch={id:string;code:string;nameAr:string;nameEn?:string|null;addressAr?:string|null;addressEn?:string|null;phone?:string|null;isActive:boolean;acceptsOrders:boolean;isOpenOverride?:boolean|null;_count?:{branchProducts:number}};
type Promotion={id:string;name:string;code?:string|null;type:string;value:string;scope:string;isActive:boolean;startsAt?:string|null;endsAt?:string|null};
type Customer={id:string;fullName?:string|null;phone?:string|null;email?:string|null;createdAt:string;isActive:boolean;orders:{id:string;total:string;createdAt:string;branch:{id:string;nameAr:string;nameEn?:string|null}}[]};
type Order={id:string;orderNumber:string;status:string;pickupMethod:string;total:string;createdAt:string;customer?:Customer|null;branch:Branch;items:{id:string;productName:string;quantity:number;lineTotal:string}[]};
type Report={totalSales:number;orders:number;averageOrderValue:number;cancelled:number;topProducts:{name:string;qty:number;sales:number}[];recentOrders:Order[]};
type Setting={key:string;value:string};

const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:3000/v1';
const NAV:[Tab,string,string][]=[['dashboard','Dashboard','Overview'],['orders','Live Orders','Kitchen flow'],['products','Menu & Products','Catalog'],['categories','Categories','Menu structure'],['modifiers','Modifiers','Sizes & extras'],['branches','Branches','Stores'],['availability','Availability','Sold out controls'],['promotions','Promotions','Offers'],['customers','Customers','CRM'],['reports','Reports','Sales'],['settings','Settings','System']];
const ACTION:Partial<Record<Tab,string>>={products:'+ New Product',categories:'+ Add Category',modifiers:'+ Add Modifier',branches:'+ Add Branch',promotions:'+ New Promotion'};

export default function AdminHome(){
 const [token,setToken]=useState(''); const [authReady,setAuthReady]=useState(false); const [loginError,setLoginError]=useState('');
 const [tab,setTab]=useState<Tab>('dashboard'); const [loading,setLoading]=useState(false); const [message,setMessage]=useState('');
 const [products,setProducts]=useState<Product[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [branches,setBranches]=useState<Branch[]>([]); const [groups,setGroups]=useState<ModifierGroup[]>([]); const [promotions,setPromotions]=useState<Promotion[]>([]); const [customers,setCustomers]=useState<Customer[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [settings,setSettings]=useState<Setting[]>([]); const [report,setReport]=useState<Report|null>(null);
 const [selectedProduct,setSelectedProduct]=useState<Product|null>(null); const [imageUrl,setImageUrl]=useState(''); const [uploading,setUploading]=useState(false); const [selectedBranch,setSelectedBranch]=useState(''); const [search,setSearch]=useState('');
 useEffect(()=>{setToken(sessionStorage.getItem('lmtd_admin_token')||'');setAuthReady(true)},[]);
 async function apiFetch(path:string,init:RequestInit={}){const h=new Headers(init.headers||{});h.set('Authorization',`Bearer ${token}`);return fetch(`${API}${path}`,{...init,headers:h})}
 async function load(){if(!token)return;setLoading(true);try{const rs=await Promise.all(['/admin/catalog/products','/admin/catalog/categories','/admin/catalog/branches','/admin/catalog/modifier-groups','/admin/catalog/promotions','/admin/catalog/customers','/admin/catalog/orders','/admin/catalog/settings','/admin/catalog/reports'].map(p=>apiFetch(p,{cache:'no-store'})));if(rs.some(r=>r.status===401)){logout();return}if(rs.some(r=>!r.ok))throw new Error('api');const [p,c,b,g,pr,cu,o,s,re]=await Promise.all(rs.map(r=>r.json()));setProducts(p);setCategories(c);setBranches(b);setGroups(g);setPromotions(pr);setCustomers(cu);setOrders(o);setSettings(s);setReport(re);if(!selectedBranch&&b[0])setSelectedBranch(b[0].id);setMessage('')}catch{setMessage('تعذر تحميل بعض بيانات LMTD. تأكد من تحديث الـAPI.')}finally{setLoading(false)}}
 useEffect(()=>{if(token)load()},[token]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoginError('');const fd=new FormData(e.currentTarget);try{const r=await fetch(`${API}/admin/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:String(fd.get('username')||''),password:String(fd.get('password')||'')})});if(!r.ok){setLoginError('اسم المستخدم أو كلمة المرور غير صحيحة.');return}const d=await r.json();sessionStorage.setItem('lmtd_admin_token',d.accessToken);setToken(d.accessToken)}catch{setLoginError('تعذر الاتصال بخدمة الدخول.')}}
 function logout(){sessionStorage.removeItem('lmtd_admin_token');setToken('')}
 async function json(path:string,method:string,body?:unknown){const r=await apiFetch(path,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok){setMessage('تعذر حفظ التغيير.');return false}await load();return true}
 function pageAction(){if(tab==='products'){setSelectedProduct({} as Product);setImageUrl('')}else document.getElementById(`${tab}-form`)?.scrollIntoView({behavior:'smooth'})}
 async function upload(file:File){if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setMessage('استخدم JPG أو PNG أو WEBP.');return}setUploading(true);try{const r=await apiFetch('/admin/media/presign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,contentType:file.type})});if(!r.ok)throw new Error();const {uploadUrl,publicUrl}=await r.json();const u=await fetch(uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!u.ok)throw new Error();setImageUrl(publicUrl)}catch{setMessage('رفع الصور يحتاج Object Storage.')}finally{setUploading(false)}}
 const filteredProducts=useMemo(()=>products.filter(p=>(p.nameEn||p.nameAr||'').toLowerCase().includes(search.toLowerCase())||p.sku.toLowerCase().includes(search.toLowerCase())),[products,search]);
 const activeProducts=products.filter(p=>p.isActive).length; const selectedBranchObj=branches.find(b=>b.id===selectedBranch);
 if(!authReady)return null;
 if(!token)return <main className="loginShell"><section className="loginCard"><div className="loginBrand"><b>LMTD</b><span>OWNER CONSOLE</span></div><h1>Welcome back.</h1><p>Sign in to manage LMTD operations.</p><form onSubmit={login}><label>Username<input name="username" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label>{loginError&&<div className="loginError">{loginError}</div>}<button className="dark">Sign in</button></form><small>Protected owner access</small></section></main>;
 return <main className="ops"><aside className="side"><div className="sideBrand"><b>LMTD</b><span>CONTROL</span></div><div className="storePicker"><small>Access</small><strong>Owner</strong><span>All UAE Branches</span></div><nav>{NAV.map(([id,label,sub])=><button key={id} className={tab===id?'on':''} onClick={()=>setTab(id)}><span>{label}</span><small>{sub}</small></button>)}</nav><button className="logout" onClick={logout}>Sign out</button></aside><section className="work"><header className="top"><div><small>LMTD COFFEE</small><strong>{NAV.find(x=>x[0]===tab)?.[1]}</strong></div><div className="topActions"><button onClick={load}>Refresh</button>{ACTION[tab]&&<button className="dark" onClick={pageAction}>{ACTION[tab]}</button>}</div></header><div className="page">{message&&<div className="notice">{message}</div>}{loading&&<div className="notice">Refreshing live data…</div>}

 {tab==='dashboard'&&<><section className="heroAdmin"><div><p>Owner console</p><h1>Store operations at a glance.</h1><span>Live data from LMTD PostgreSQL.</span></div><button className="dark" onClick={()=>setTab('orders')}>Open live orders</button></section><section className="kpis"><article><span>Products</span><b>{products.length}</b><small>{activeProducts} active</small></article><article><span>Branches</span><b>{branches.length}</b><small>{branches.filter(b=>b.acceptsOrders&&b.isActive).length} accepting orders</small></article><article><span>Customers</span><b>{customers.length}</b><small>registered</small></article><article><span>Orders</span><b>{orders.length}</b><small>loaded from database</small></article></section></>}

 {tab==='products'&&<section className="catalogGrid"><div className="card"><div className="cardTitle"><div><h1>Menu & Products</h1><p>Current customer menu, grouped and editable.</p></div><button className="dark" onClick={()=>{setSelectedProduct({} as Product);setImageUrl('')}}>+ Add item</button></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search product or SKU"/>{filteredProducts.length===0?<Empty text="No products yet. Add the first menu item."/>:<div className="productList">{filteredProducts.map(p=><article key={p.id}><div className="thumb">{p.imageUrl?<img src={p.imageUrl} alt=""/>:<span>IMG</span>}</div><div className="grow"><b>{p.nameEn||p.nameAr}</b><span>{p.category?.nameEn||p.category?.nameAr||'Uncategorized'} · AED {Number(p.basePrice).toFixed(2)}</span><small>{p.sku}</small></div><span className={p.isActive?'pill green':'pill'}>{p.isActive?'Active':'Hidden'}</span><button onClick={()=>{setSelectedProduct(p);setImageUrl(p.imageUrl||'')}}>Edit</button><button onClick={()=>json(`/admin/catalog/products/${p.id}`,'DELETE')}>Hide</button></article>)}</div>}</div><div className="card editor"><h2>{selectedProduct?.id?'Edit product':'Product editor'}</h2>{!selectedProduct?<Empty text="Select a product or add a new one."/>:<ProductForm product={selectedProduct} categories={categories} imageUrl={imageUrl} uploading={uploading} upload={upload} cancel={()=>setSelectedProduct(null)} save={async body=>{const ok=await json(selectedProduct.id?`/admin/catalog/products/${selectedProduct.id}`:'/admin/catalog/products',selectedProduct.id?'PATCH':'POST',body);if(ok){setSelectedProduct(null);setImageUrl('')}}}/>}</div></section>}

 {tab==='categories'&&<section className="card full"><div className="cardTitle"><div><h1>Categories</h1><p>Current menu structure. New categories join this same list immediately.</p></div></div><form id="categories-form" className="inline" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await json('/admin/catalog/categories','POST',{nameAr:String(f.get('nameAr')),nameEn:String(f.get('nameEn')||''),sortOrder:categories.length,isActive:true}))e.currentTarget.reset()}}><input name="nameAr" placeholder="Arabic category name" required/><input name="nameEn" placeholder="English category name"/><button className="dark">Add category</button></form><div className="rows">{categories.map(c=><div className="dataRow" key={c.id}><div><b>{c.nameEn||c.nameAr}</b><span>{c.nameAr} · {c._count?.products||0} products</span></div><span className={c.isActive?'pill green':'pill'}>{c.isActive?'Active':'Hidden'}</span><button onClick={()=>{const n=prompt('Category name',c.nameEn||c.nameAr);if(n)json(`/admin/catalog/categories/${c.id}`,'PATCH',{nameEn:n})}}>Edit</button><button onClick={()=>json(`/admin/catalog/categories/${c.id}`,'DELETE')}>Hide</button></div>)}</div></section>}

 {tab==='modifiers'&&<section className="card full"><div className="cardTitle"><div><h1>Modifiers</h1><p>Sizes, milk, extras and customer choices linked to real products.</p></div></div><form id="modifiers-form" className="form compact" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await json('/admin/catalog/modifier-groups','POST',{productId:String(f.get('productId')),nameAr:String(f.get('nameAr')),nameEn:String(f.get('nameEn')||''),selectionType:String(f.get('selectionType')),isRequired:f.get('isRequired')==='on'}))e.currentTarget.reset()}}><div className="three"><label>Product<select name="productId" required>{products.map(p=><option key={p.id} value={p.id}>{p.nameEn||p.nameAr}</option>)}</select></label><label>Group name<input name="nameEn" placeholder="Milk / Size"/><input name="nameAr" placeholder="Arabic name" required/></label><label>Selection<select name="selectionType"><option value="SINGLE">Single</option><option value="MULTIPLE">Multiple</option></select><span className="check"><input type="checkbox" name="isRequired"/> Required</span></label></div><button className="dark">Add modifier group</button></form>{groups.length===0?<Empty text="No modifier groups yet."/>:<div className="groupGrid">{groups.map(g=><article className="modifierCard" key={g.id}><header><div><small>{g.product.nameEn||g.product.nameAr}</small><h3>{g.nameEn||g.nameAr}</h3><span>{g.selectionType} · {g.isRequired?'Required':'Optional'}</span></div><button onClick={()=>json(`/admin/catalog/modifier-groups/${g.id}`,'DELETE')}>Disable</button></header><div className="optionList">{g.modifiers.map(m=><div key={m.id}><span>{m.nameEn||m.nameAr}</span><b>{Number(m.priceDelta)>0?`+ AED ${Number(m.priceDelta).toFixed(2)}`:'Included'}</b><button onClick={()=>json(`/admin/catalog/modifiers/${m.id}`,'PATCH',{isActive:!m.isActive})}>{m.isActive?'Disable':'Enable'}</button></div>)}</div><form className="miniForm" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await json('/admin/catalog/modifiers','POST',{modifierGroupId:g.id,nameAr:String(f.get('nameAr')),nameEn:String(f.get('nameEn')||''),priceDelta:Number(f.get('priceDelta')||0)}))e.currentTarget.reset()}}><input name="nameAr" placeholder="Arabic option" required/><input name="nameEn" placeholder="English option"/><input name="priceDelta" type="number" step="0.01" placeholder="AED +"/><button>Add option</button></form></article>)}</div>}</section>}

 {tab==='branches'&&<section className="card full"><div className="cardTitle"><div><h1>Branches</h1><p>Current stores, addresses and order controls.</p></div></div><form id="branches-form" className="form compact" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await json('/admin/catalog/branches','POST',{code:String(f.get('code')),nameAr:String(f.get('nameAr')),nameEn:String(f.get('nameEn')||''),addressAr:String(f.get('addressAr')||''),addressEn:String(f.get('addressEn')||''),acceptsOrders:true,isActive:true}))e.currentTarget.reset()}}><div className="three"><label>Branch code<input name="code" required placeholder="LMTD-BTN"/></label><label>Arabic name<input name="nameAr" required/></label><label>English name<input name="nameEn"/></label></div><div className="two"><label>Arabic address<input name="addressAr"/></label><label>English address<input name="addressEn"/></label></div><button className="dark">Add branch</button></form><div className="branchCards">{branches.map(b=><article key={b.id}><div><span className={b.isActive?'pill green':'pill'}>{b.isActive?'Active':'Disabled'}</span><h2>{b.nameEn||b.nameAr}</h2><p>{b.addressEn||b.addressAr||'No address yet'}</p><small>{b.code}</small></div><div className="branchActions"><button className={b.acceptsOrders?'statusOn':'statusOff'} onClick={()=>json(`/admin/catalog/branches/${b.id}`,'PATCH',{acceptsOrders:!b.acceptsOrders})}>{b.acceptsOrders?'Accepting orders':'Orders paused'}</button><button onClick={()=>json(`/admin/catalog/branches/${b.id}`,'PATCH',{isActive:!b.isActive})}>{b.isActive?'Disable':'Enable'}</button></div></article>)}</div></section>}

 {tab==='availability'&&<section className="card full"><div className="cardTitle"><div><h1>Availability</h1><p>Manual only. Sold Out stays closed until you reopen it.</p></div><select value={selectedBranch} onChange={e=>setSelectedBranch(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.nameEn||b.nameAr}</option>)}</select></div>{!selectedBranchObj?<Empty text="Add a branch first."/>:<><h3>{selectedBranchObj.nameEn||selectedBranchObj.nameAr} · Products</h3><div className="availGrid">{products.filter(p=>p.isActive).map(p=>{const bp=p.branchProducts.find(x=>x.branchId===selectedBranch);const on=bp?.isAvailable!==false;return <button key={p.id} className={on?'avail yes':'avail no'} onClick={()=>json(`/admin/catalog/branches/${selectedBranch}/products/${p.id}`,'PATCH',{isAvailable:!on})}><span>{p.nameEn||p.nameAr}</span><b>{on?'AVAILABLE':'SOLD OUT'}</b></button>})}</div><h3>Modifiers</h3><div className="availGrid">{groups.flatMap(g=>g.modifiers).filter(m=>m.isActive).map(m=>{const bm=m.branchModifiers.find(x=>x.branchId===selectedBranch);const on=bm?.isAvailable!==false;return <button key={m.id} className={on?'avail yes':'avail no'} onClick={()=>json(`/admin/catalog/branches/${selectedBranch}/modifiers/${m.id}`,'PATCH',{isAvailable:!on})}><span>{m.nameEn||m.nameAr}</span><b>{on?'AVAILABLE':'SOLD OUT'}</b></button>})}</div></>}</section>}

 {tab==='promotions'&&<section className="card full"><div className="cardTitle"><div><h1>Promotions</h1><p>Real offers saved in PostgreSQL.</p></div></div><form id="promotions-form" className="form compact" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await json('/admin/catalog/promotions','POST',{name:String(f.get('name')),code:String(f.get('code')||'')||undefined,type:String(f.get('type')),value:Number(f.get('value')||0),scope:'ALL',isActive:true}))e.currentTarget.reset()}}><div className="four"><label>Name<input name="name" required/></label><label>Code<input name="code" placeholder="Optional"/></label><label>Type<select name="type"><option value="PERCENT">Percentage %</option><option value="FIXED">Fixed AED</option><option value="BUY_X_GET_Y">Buy X Get Y</option></select></label><label>Value<input name="value" type="number" step="0.01" required/></label></div><button className="dark">Create promotion</button></form><div className="rows">{promotions.map(p=><div className="dataRow" key={p.id}><div><b>{p.name}</b><span>{p.code||'Automatic'} · {p.type} · {p.value}</span></div><span className={p.isActive?'pill green':'pill'}>{p.isActive?'Active':'Inactive'}</span><button onClick={()=>json(`/admin/catalog/promotions/${p.id}`,'PATCH',{isActive:!p.isActive})}>{p.isActive?'Disable':'Enable'}</button><button onClick={()=>json(`/admin/catalog/promotions/${p.id}`,'DELETE')}>Hide</button></div>)}</div></section>}

 {tab==='customers'&&<section className="card full"><div className="cardTitle"><div><h1>Customers</h1><p>Registered customers and real order history.</p></div></div>{customers.length===0?<Empty text="No registered customers yet."/>:<div className="rows">{customers.map(c=>{const spend=c.orders.reduce((s,o)=>s+Number(o.total),0);return <div className="dataRow customerRow" key={c.id}><div><b>{c.fullName||c.phone||c.email||'Customer'}</b><span>{c.phone||c.email||'No contact'} · joined {new Date(c.createdAt).toLocaleDateString()}</span></div><div className="metric"><b>{c.orders.length}</b><small>orders</small></div><div className="metric"><b>AED {spend.toFixed(2)}</b><small>lifetime</small></div></div>})}</div>}</section>}

 {tab==='orders'&&<section className="card full"><div className="cardTitle"><div><h1>Live Orders</h1><p>Orders from the database, newest first.</p></div></div>{orders.length===0?<Empty text="No orders yet. New customer orders will appear here."/>:<div className="orderGrid">{orders.map(o=><article key={o.id}><header><b>#{o.orderNumber}</b><span className="pill">{o.status}</span></header><h3>{o.branch.nameEn||o.branch.nameAr}</h3><p>{o.items.map(i=>`${i.quantity}× ${i.productName}`).join(', ')}</p><footer><span>{o.pickupMethod}</span><b>AED {Number(o.total).toFixed(2)}</b></footer></article>)}</div>}</section>}

 {tab==='reports'&&<section className="card full"><div className="cardTitle"><div><h1>Reports</h1><p>Only real order data. No demo numbers.</p></div></div><div className="reportKpis"><article><span>Total Sales</span><b>AED {(report?.totalSales||0).toFixed(2)}</b></article><article><span>Orders</span><b>{report?.orders||0}</b></article><article><span>Average Order</span><b>AED {(report?.averageOrderValue||0).toFixed(2)}</b></article><article><span>Cancelled / Refunded</span><b>{report?.cancelled||0}</b></article></div><div className="twoPanels"><div><h2>Top Products</h2>{report?.topProducts.length?<div className="rows">{report.topProducts.map((p,i)=><div className="dataRow" key={`${p.name}-${i}`}><div><b>{p.name}</b><span>{p.qty} sold</span></div><b>AED {p.sales.toFixed(2)}</b></div>)}</div>:<Empty text="No sales in the selected data yet."/>}</div><div><h2>Recent Orders</h2>{report?.recentOrders.length?<div className="rows">{report.recentOrders.slice(0,8).map(o=><div className="dataRow" key={o.id}><div><b>#{o.orderNumber}</b><span>{o.status}</span></div><b>AED {Number(o.total).toFixed(2)}</b></div>)}</div>:<Empty text="No orders yet."/>}</div></div></section>}

 {tab==='settings'&&<SettingsPanel settings={settings} save={(key,value)=>json(`/admin/catalog/settings/${encodeURIComponent(key)}`,'PATCH',{value})}/>} </div></section></main>
}

function Empty({text}:{text:string}){return <div className="emptyState"><div><b>Nothing to show</b><span>{text}</span></div></div>}
function ProductForm({product,categories,imageUrl,uploading,upload,cancel,save}:{product:Product;categories:Category[];imageUrl:string;uploading:boolean;upload:(f:File)=>void;cancel:()=>void;save:(b:unknown)=>Promise<void>}){return <form className="form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await save({sku:String(f.get('sku')),nameAr:String(f.get('nameAr')),nameEn:String(f.get('nameEn')||''),descriptionAr:String(f.get('descriptionAr')||''),imageUrl,basePrice:Number(f.get('basePrice')||0),categoryId:String(f.get('categoryId')||'')||undefined,isActive:f.get('isActive')==='on'})}}><label>Product image<div className="uploadBox">{imageUrl?<img src={imageUrl} alt="preview"/>:<div><b>Upload product image</b><span>JPG, PNG or WEBP</span></div>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></div>{uploading&&<small>Uploading…</small>}</label><div className="two"><label>Arabic name<input name="nameAr" required defaultValue={product.nameAr||''}/></label><label>English name<input name="nameEn" defaultValue={product.nameEn||''}/></label></div><div className="two"><label>SKU<input name="sku" required defaultValue={product.sku||''}/></label><label>Price AED<input name="basePrice" type="number" step="0.01" required defaultValue={product.basePrice||''}/></label></div><label>Category<select name="categoryId" defaultValue={product.categoryId||product.category?.id||''}><option value="">Uncategorized</option>{categories.map(c=><option key={c.id} value={c.id}>{c.nameEn||c.nameAr}</option>)}</select></label><label>Description<textarea name="descriptionAr" rows={4} defaultValue={product.descriptionAr||''}/></label><label className="check"><input type="checkbox" name="isActive" defaultChecked={product.id?product.isActive:true}/> Visible in customer menu</label><div className="formBtns"><button type="button" onClick={cancel}>Cancel</button><button className="dark">Save product</button></div></form>}
function SettingsPanel({settings,save}:{settings:Setting[];save:(k:string,v:string)=>Promise<boolean>}){const map=Object.fromEntries(settings.map(s=>[s.key,s.value]));const fields=[['brand_name','Brand name',map.brand_name||'LMTD'],['currency','Currency',map.currency||'AED'],['timezone','Timezone',map.timezone||'Asia/Dubai'],['languages','Languages',map.languages||'ar,en'],['pickup_methods','Pickup methods',map.pickup_methods||'walk_in,drive_pickup'],['receipt_footer','Receipt footer',map.receipt_footer||'Thank you for choosing LMTD']];return <section className="card full"><div className="cardTitle"><div><h1>Settings</h1><p>System settings stored in the database.</p></div></div><div className="settingsGrid">{fields.map(([key,label,value])=><form key={key} className="settingCard" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await save(key,String(f.get('value')||''))}}><label>{label}<input name="value" defaultValue={value}/></label><button>Save</button></form>)}</div><div className="securityBox"><h2>Admin & Security</h2><p>Owner authentication is active. Role-based Manager / Staff access can be added without exposing payment credentials.</p></div></section>}
